export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_REJECTED = 'FETCH_USERS_REJECTED';
export const FETCH_USERS_PENDING = 'FETCH_USERS_PENDING';
export const SELECT_NEW_EMPLOYEE = 'SELECT_NEW_EMPLOYEE';
export const DELETE_EMPLOYEE_ID = 'DELETE_EMPLOYEE_ID';
